cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'ruby-build'
brew 'rbenv'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'less'

cask 'atom'
cask 'google-chrome'
cask 'slack'
cask 'spotify'
